#!/bin/bash
cp template.html q.html
while read l
do
    THINGS=`echo "$l" | grep -o -E "[a-Z\-]+"`
    echo "$THINGS"
    TITLE=`echo "$THINGS" | head -n -1`
    REPO=`echo "$THINGS" | tail -n 1`
    LINK="https://github.com/jaq-the-cat/$REPO"
    echo "<a class=\"project\" href=\"$LINK\">" >> q.html
    echo "<h2>$TITLE</h2>" >> q.html
    echo "<small>$LINK</small>" >> q.html
    echo "</a>" >> q.html
done <projects.txt
